# Generated by Django 3.0.4 on 2020-03-24 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200229_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adress',
            name='pelak',
            field=models.CharField(max_length=100),
        ),
    ]
