# Generated by Django 2.2.9 on 2020-01-27 10:15

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_product_brand'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='values',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
