# Generated by Django 3.0.4 on 2020-03-25 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200325_1545'),
        ('content', '0003_auto_20200325_0205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productunit',
            name='seller',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='users.SupplierUser', verbose_name='فروشنده'),
        ),
    ]
