# Generated by Django 2.2.9 on 2020-02-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_auto_20200205_0829'),
    ]

    operations = [
        migrations.AddField(
            model_name='productunit',
            name='variant_title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
