# Generated by Django 3.0.4 on 2020-03-24 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0003_auto_20200325_0205'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20200325_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('shipping_status', models.CharField(choices=[('pending', 'Waiting for paying'), ('canceled', 'Cancled order'), ('unsuccessful', 'Unsuccessfull payment'), ('successful', 'Successful payment'), ('sent', 'Sent to Customer'), ('delivered', 'Delivered to custumer')], default='pending', max_length=21)),
                ('total_price', models.PositiveIntegerField()),
                ('address', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='users.Adress')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('main_image_path', models.ImageField(upload_to='orderimages/')),
                ('product_name', models.CharField(max_length=255)),
                ('product_unit_price', models.PositiveIntegerField()),
                ('seller', models.CharField(max_length=255)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderitems', to='shipping.Order')),
                ('product_unit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='content.ProductUnit')),
            ],
        ),
    ]
